//
// Created by chappie on 20.04.2022.
//

#ifndef MC_INVENTORY_MOCKUP_UNSTACKABLEITEM_H
#define MC_INVENTORY_MOCKUP_UNSTACKABLEITEM_H


class UnstackableItem {

};


#endif //MC_INVENTORY_MOCKUP_UNSTACKABLEITEM_H
